apiVersion: actions.odigos.io/v1alpha1
kind: LatencySampler
metadata:
  name: frontend-latency-sampler
  namespace: odigos-system
spec:
  endpoints_filters:
    - service_name: frontend
      http_route: /keepalive
      minimum_latency_threshold: 3000
      fallback_sampling_ratio: 0
  signals:
    - TRACES
