apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: namespace-source-kv-mall-infra
  namespace: kv-mall-infra
spec:
  workload:
    name: kv-mall-infra
    namespace: kv-mall-infra
    kind: Namespace
