name: Deploy Odigos Observability Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Odigos Helm repo (if not already added)
        run: |
          helm repo add odigos https://keyval-dev.github.io/odigos-charts || true
          helm repo update

      - name: Install Odigos via Helm
        run: |
          helm upgrade --install odigos odigos/odigos \
            --namespace odigos-system --create-namespace \
            --wait

      - name: Apply Jaeger Destination
        run: kubectl apply -f odigos/destination-jaeger.yaml

      - name: Apply Source for kv-mall namespace
        run: kubectl apply -f odigos/source-kv-mall.yaml

      - name: Apply Source for kv-mall-infra namespace
        run: kubectl apply -f odigos/source-kv-mall-infra.yaml

      - name: Apply LatencySampler for frontend
        run: kubectl apply -f odigos/latency-sampler-frontend.yaml

      - name: Apply InstrumentationRule for UI services
        run: kubectl apply -f odigos/instrumentation-rule-ui.yaml
